services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: ./mm_project
    command: ["gunicorn", "--bind", "0.0.0.0:80", "--worker-class", "gevent", "mm_project.wsgi:application"]
    volumes:
      - ./mm_project:/app
    ports:
      - "${DJANGO_PORT}:80"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=mm_project.settings.default
    depends_on:
      - db

volumes:
  postgres_data:
